name: Test

on:
  pull_request:
    branches: [master]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Initialize npm
        run: npm init -y

      - name: Install Dependencies
        run: npm install hardhat @nomiclabs/hardhat-ethers chai ethers --save-dev

      - name: Run Tests
        run: npx hardhat test
